language: dart

# This is the last dev version prior to dart 2 being moved to the stable
# version line.
dart:
  - stable

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

dart:
  - 2.4.1
  - stable
  - dev

install:
  - pub get
  - npm install

script:
  - dartanalyzer .
  - dartfmt -n --set-exit-if-changed .
  - pub run dependency_validator
  - ./tool/test.sh
