language: dart

dart:
  - stable
  - dev

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

install:
- pub get
- npm install

script:
- pub run dart_dev format --check
- pub run dart_dev analyze
- pub run dependency_validator -i browser,coverage,dart_style
- ./tool/travis.sh test

addons:
  chrome: stable
