language: dart

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

install:
  - pub get
  - npm install

jobs:
  include:
    - dart: 2.4.1
      name: "SDK: 2.4.1"
      script:
        - dartanalyzer .
        - pub run dart_dev test
    - dart: stable
      name: "SDK: stable"
      script:
        - dartanalyzer .
        - dartfmt -n --set-exit-if-changed .
        - pub run dependency_validator
        - pub run dart_dev test
    - dart: dev
      name: "SDK: dev"
      script:
        - dartanalyzer .
        - pub run dart_dev test
