language: dart

# This is the last dev version prior to dart 2 being moved to the stable
# version line.
dart:
  - 1.24.3
  - 2.0.0-dev.69.5

# Workaround for issue with sandboxed Chrome in containerized Travis builds.
sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

install:
  - pub get
  - npm install

script:
  - dartanalyzer .
  - dartfmt -n --set-exit-if-changed .
  - pub run dependency_validator -i browser,build_runner,build_test,build_web_compilers,coverage,dart_style
  - ./tool/test.sh
