targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "test/**_test.dart.browser_test.dart"
            - "example/main.dart"
        release_options:
          dart2js_args:
          - --no-minify
