name: sockjs_client_wrapper
version: 1.1.0
description: A Dart wrapper for the `sockjs-client` JS library.
homepage: https://github.com/Workiva/sockjs_client_wrapper

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  js: ^0.6.1
  w_common: ^1.20.1

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^0.10.9
  build_web_compilers: ^2.5.1
  dart_dev: ^3.0.0
  dependency_validator: ^2.0.1
  test: ^1.9.1
  workiva_analysis_options: ^1.1.0
