name: sockjs_client_wrapper
version: 1.0.9
description: A Dart wrapper for the `sockjs-client` JS library.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
homepage: https://github.com/Workiva/sockjs_client_wrapper

environment:
  sdk: '>=1.24.2 <3.0.0'

dependencies:
  js: ^0.6.1
  w_common: ^1.9.0
  
dev_dependencies:
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ">=0.9.0 <1.0.0"
  build_web_compilers: ">=0.2.0 <3.0.0"
  coverage: '>=0.10.0 <0.13.0'
  dart_dev: ^2.0.0
  dart_style: ^1.0.8
  dependency_validator: ^1.2.1
  test: ">=0.12.30 <2.0.0"

transformers:
- test/pub_serve:
    $include: test/**_test.dart
