name: sockjs_client_wrapper
version: 2.0.0
description: A Dart wrapper for the `sockjs-client` JS library.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
homepage: https://github.com/Workiva/sockjs_client_wrapper

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  js: ^0.6.1
  w_common:
    git:
      url: https://github.com/zmeggyesi/w_common.git
      ref: flutter-2-migration

dependency_overrides:
  logging: ^1.0.1
  glob: ^2.0.1
  args: ^2.0.0
  watcher: ^1.0.0
  package_config: ^2.0.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  dart_dev: ^3.6.4
#  dependency_validator: ^2.0.1
  test: ^1.9.1
  workiva_analysis_options: ^1.1.0
