name: sockjs_client_wrapper
version: 0.0.0

dependencies:
  js: ^0.6.1
  logging: ^0.11.3
  w_common: ^1.9.0
  
dev_dependencies:
  browser: ^0.10.0+2
  coverage: ^0.9.3
  dart_dev: ^1.8.1
  dart_style: ^1.0.8
  test: ^0.12.27+1

transformers:
- test/pub_serve:
    $include: test/**_test.dart
