name: sockjs_client_wrapper
version: 1.1.3
description: A Dart wrapper for the `sockjs-client` JS library.
homepage: https://github.com/Workiva/sockjs_client_wrapper

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  js: ^0.6.1
  w_common: ^1.20.1

dev_dependencies:
  build_runner: ^1.10.0
  build_test: '>=0.10.9 <2.0.0'
  build_web_compilers: ^2.12.0
  dart_dev: ^3.6.5
  dependency_validator: ^2.0.1
  test: ^1.15.7
  workiva_analysis_options: ^1.1.0
