name: sockjs_client_wrapper
version: 1.1.0
description: A Dart wrapper for the `sockjs-client` JS library.
authors:
  - Workiva Client Platform Team <clientplatform@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
homepage: https://github.com/Workiva/sockjs_client_wrapper

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  js: ^0.6.1
  w_common:
    git:
      url: git@github.com:Workiva/w_common.git
      ref: w-common-flutter-fix-new

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^2.0.0
  build_web_compilers: ^2.5.1
  package_resolver:
    git:
      url: git@github.com:kyleferguson-wk/package_resolver.git
      ref: master
  dart_dev:
    git:
      url: git@github.com:kyleferguson-wk/dart_dev.git
      ref: master
  dependency_validator:
    git:
        url: git@github.com:kyleferguson-wk/dependency_validator.git
        ref: master
  test: ^1.9.1
  workiva_analysis_options: ^1.1.0
