name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk:
          - 2.19.6
          # Commented out until we upgrade to Dart 3
          # - beta
          # - dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install Node dependencies
        run: npm install
      - name: Install Dart dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == '2.19.6' }}
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart run dart_dev test
      - uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
