name: Dart CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ stable, beta, dev ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install Node dependencies
        run: npm install
      - name: Install Dart dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'stable' }}
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart run dart_dev test

  test_old_sdks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [2.7.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install Node dependencies
        run: npm install
      - name: Install Dart dependencies
        run: pub get
      - name: Validate dependencies
        run: pub run dependency_validator
      - name: Analyze project source
        run: dartanalyzer .
      - name: Run tests
        run: pub run dart_dev test
